### ISSUE TITLE
missing contribution.md

### ISSUE THREAD

**Issue by Suppandi-1** [Anupkjha2601/foodie-blog#1]
Add a contribution.md file to this projects . 
Please Assigne this issue to my another account 
@Devesh-Daku

**Comment by Anupkjha2601** [comment]
please write here this issue with your @Devesh-Daku so that i can assign

**Comment by Devesh-Daku** [comment]
I'd like to resolve the issue

**Comment by Yash-Ainapure** [comment]
@Anupkjha2601 , I would like to take this issue .
