### ISSUE TITLE
Bug : Cards sizes are not uniform.

### ISSUE THREAD

**Issue by darishkhan** [Anupkjha2601/foodie-blog#10]
<img width="955" alt="Screenshot 2023-12-11 112136" src="https://github.com/Anupkjha2601/foodie-blog/assets/93848997/884b86d2-fb16-429c-a27d-dcede36b2fe4">

- Implement uniform card size for the whole carousel.

**Comment by darishkhan** [comment]
I would like to work on this issue.

**Comment by itsmeabhishek03** [comment]
can i work on this issue?

**Comment by darishkhan** [comment]
I have made a Pull Request. Please verify @Anupkjha2601
