### ISSUE TITLE
Implementing a hover effect on social media icons.

### ISSUE THREAD

**Issue by Ayusht777** [Anupkjha2601/foodie-blog#21]
When a person hovers over the icon, both the icon and the text should change to the respective brand color.
![image](https://github.com/Anupkjha2601/foodie-blog/assets/106388215/51681a66-19b6-45f5-9adb-908aa43b3ee7)

**Comment by itsmeabhishek03** [comment]
Can I work on this?

**Comment by maadi7** [comment]
@Ayusht777 hii, I would like to work on this issue may you please assign this to me.

**Comment by Ayusht777** [comment]
@maadi7  @itsmeabhishek03  I am a contributor, similar to you, not the owner of this project.
