### ISSUE TITLE
Feat : Feedback Page

### ISSUE THREAD

**Issue by drockparashar** [Anupkjha2601/foodie-blog#27]
Adding a feedback page on this website would be great for reviews from customers. I would be contributing under Codepeak 23.

**Comment by RonitBaranwal** [comment]
Is anyone working on this issue or may I work on it?

**Comment by Yash-Ainapure** [comment]
@Anupkjha2601 , As there is no response from assigned one's , I would like to take this issue up.

**Comment by pooranjoyb** [comment]
Hey as this issue is still open and today's the end of the event. I'd like to take this issue. Could you please assign me this? @Anupkjha2601
