### ISSUE TITLE
Fix Search Icon in Contact Page

### ISSUE THREAD

**Issue by smty2018** [Anupkjha2601/foodie-blog#3]
Currently the search icon is miss aligned in the contact page
![image](https://github.com/Anupkjha2601/foodie-blog/assets/74114936/e7be6fb3-9e56-433a-8a7a-bd8570117d6f)
![image](https://github.com/Anupkjha2601/foodie-blog/assets/74114936/c93aec2e-39da-4212-8eb2-342040dd0d0b)

Want to fix this 

@Anupkjha2601 Can you please assign this issue to me

**Comment by AnupK1234** [comment]
Hey, I would like to work on this issue. Kindly assign it to me.

**Comment by Tanishka023** [comment]
Hey!! I would really like to fix this issue, can you please assign it to me? @Anupkjha2601
