### ISSUE TITLE
Bug : Text Color while inputting something in Search Bar

### ISSUE THREAD

**Issue by Molik2801** [Anupkjha2601/foodie-blog#5]
Font color is Black which is nearly invisible due to background color . 

.
![Screenshot 2023-12-09 001957](https://github.com/Anupkjha2601/foodie-blog/assets/116110308/ff1cb27e-f297-4db1-a7ea-7b173e2da23b)

**Comment by Molik2801** [comment]
i would like to contribute in this also @Anupkjha2601

**Comment by FAIZMOHD1** [comment]
Right now I changed the text colour to red which i showed in attached picture . I want to contribute on this issue @Anupkjha2601 .
![Image 09-12-23 at 12 42 AM](https://github.com/Anupkjha2601/foodie-blog/assets/126939060/3717ac2e-11a8-428f-a559-e72f76fc7314)

**Comment by Molik2801** [comment]
i have made a PR 
pls check @Anupkjha2601
