### ISSUE TITLE
bug : unnecessary text

### ISSUE THREAD

**Issue by Yash-Ainapure** [Anupkjha2601/foodie-blog#52]
after opening contact page , an unnecessary text is occuring in between
I would like to fix this bug @Anupkjha2601 

![contact-bug](https://github.com/Anupkjha2601/foodie-blog/assets/136250383/281376f6-e572-48cd-a598-b26cdcce197e)

**Comment by Anupkjha2601** [comment]
@Yash-Ainapure please open link present in readme.
