### ISSUE TITLE
adding logo to login and signup page

### ISSUE THREAD

**Issue by Komal73** [Anupkjha2601/foodie-blog#53]
to add logo to login and signup pages so as to show the identity and orienting the user

**Comment by Komal73** [comment]
@Anupkjha2601 kindly assign this issue under codepeak23

**Comment by Anupkjha2601** [comment]
@Komal73 where you want to add logo

**Comment by Komal73** [comment]
the login and signup pages do not have logo. the logo should be on the left top corner
