### ISSUE TITLE
improper dark mode on navbar

### ISSUE THREAD

**Issue by Yash-Ainapure** [Anupkjha2601/foodie-blog#58]
![Screenshot (150)](https://github.com/Anupkjha2601/foodie-blog/assets/136250383/e49bf0e0-5aca-4c8c-902b-ee05757277f7)

@Anupkjha2601 , I would like to take this issue up.

**Comment by Anupkjha2601** [comment]
@Yash-Ainapure someone already working on dark mode issue, you can improve the homepage complete setting like in middle of homepage pictures are very big reduce size and do  some improvements.

**Comment by Yash-Ainapure** [comment]
> @Yash-Ainapure someone already working on dark mode issue, you can improve the homepage complete setting like in middle of homepage pictures are very big reduce size and do  some improvements.

Ok
